classdef LipidPhaseSegmentizer < handle
    % LIPIDPHASESEGMENTIZER A class for interactive segmentation of lipid phases
    % (e.g., Lo and Ld) in membrane images.
    %
    % This class manages the GUI, data loading, image processing steps
    % (like upsampling and illumination correction), and the thresholding
    % required to separate different lipid phases.
    %
    %   Copyright (c) 2017-2025 Christian Paolo Richter
    %   University of Osnabrueck
    %
    %   v1.1: Upsample Image
    %   v1.2: Toggle Boundary Option, Tooltips, Fixed a Bug in setting the Ld >= group-index (05.01.2017)

    properties(Transient)
        % --- File/Path ---
        WorkPath        % Current working directory or path (used for file operations).

        % --- Core GUI Handles ---
        hFig            % Handle to the main figure window.

        % --- Image Data Structures (RAW, PROCESSED, MASK) ---
        % These structures hold data (image matrices) and associated handles (axes, image objects, text).
        RAW             % Structure holding the raw input image data and display elements.
        PROC            % Structure holding the processed (e.g., deconvolved) image data and display elements.
        MASK            % Structure holding the final segmentation mask data and display elements.

        % --- Upsampling Control ---
        hUpsampleEdit   % Handle for the edit box controlling the upsampling factor.
        UpsampleFac = 1 % Factor by which the image is scaled for finer segmentation.

        % --- Illumination Correction Control ---
        hCorrIlluToggle % Handle for the toggle button to enable/disable illumination correction.

        % --- Deconvolution (PSF) Controls ---
        hPsfSlider      % Handle for the slider controlling the PSF width.
        hPsfEdit        % Handle for the edit box displaying the current PsfWidth.
        PsfWidth = 1.5  % Current value for the Point Spread Function (PSF) width (Gaussian standard deviation).
        PsfWidthMin = 1 % Minimum allowed value for PsfWidth.
        PsfWidthMax = 2 % Maximum allowed value for PsfWidth.

        % --- Deconvolution (Regularization/Gamma) Controls ---
        hGammaSlider    % Handle for the slider controlling the regularization (Gamma) parameter.
        hGammaEdit      % Handle for the edit box displaying the current Gamma value.
        Gamma = -3      % Current regularization parameter (e.g., log10 of lambda).
        GammaMin = -6   % Minimum allowed value for Gamma.
        GammaMax = 0    % Maximum allowed value for Gamma.

        % --- Segmentation (Multi-Otsu) Controls ---
        hNumLvlSlider   % Handle for the slider controlling the total number of intensity levels/phases.
        hNumLvlEdit     % Handle for the edit box displaying the current NumLvl.
        NumLvl = 2      % Total number of phases/levels used for multi-Otsu segmentation.
        NumLvlMin = 2   % Minimum allowed value for NumLvl.
        NumLvlMax = 5   % Maximum allowed value for NumLvl.

        % --- Phase Assignment Controls ---
        hLoLvlEdit      % Handle for the edit box specifying the index of the Lo (Liquid-Ordered) phase group.
        hLdLvlEdit      % Handle for the edit box specifying the index of the Ld (Liquid-Disordered) phase group.
        LoLvl = 1       % The numerical index/level assigned to the Lo phase (e.g., index $\le$ LoLvl are considered Lo).
        LdLvl = 2       % The numerical index/level assigned to the Ld phase (e.g., index $\ge$ LdLvl are considered Ld).
    end %properties

    methods
        %constructor
        function this = LipidPhaseSegmentizer
            % LIPIDPHASESEGMENTIZER Constructor method for the LipidPhaseSegmentizer class.
            % Initializes the object, sets up the environment, and creates the GUI.
            
            % Set the initial working path and add necessary paths.
            this.WorkPath = pwd;
            addpath(genpath(this.WorkPath)) % Add current directory and subdirectories to MATLAB path
            
            % Calculate the figure position to center it on the screen with a specific ratio/factor
            figPos = set_figure_position(1,0.85,'center');
            
            % Create the main figure window for the GUI
            this.hFig = figure('Units','pixels',...
                'Name','Lipid Phase Segmentizer v1.2',... % Set window title and version
                'NumberTitle', 'off',...
                'DockControls', 'off',...
                'MenuBar','none',... % Hide menu bar
                'Toolbar','none',... % Initially hide built-in toolbar
                'Position',figPos); % Set calculated position and size
            
            % Create a custom toolbar
            hToolbar = uitoolbar(...
                'Parent',this.hFig);
            
            % --- Toolbar Buttons ---
            
            % Load Image Button
            uipushtool(...
                'Parent', hToolbar,...
                'TooltipString','Load Image',...
                'CData', reshape([NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 NaN 0 1 1 1 1 1 0 0 0 NaN NaN 0 0 0 NaN NaN 0 1 1 1 0 0 0 0 0 NaN 0 NaN NaN NaN 0 NaN 0 1 0 0 0 0 0 0 0 NaN 0 NaN NaN NaN 0 NaN 0 1 0 0 0 0 0 0 0 NaN NaN 0 0 0 NaN NaN 0 1 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN 0 1 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 NaN 0 1 0 0 0 0 0 0 0 NaN 0 NaN 0 NaN NaN NaN 0 1 0 0 0 0 0 0 0 NaN 0 NaN 0 NaN NaN NaN 0.500000000000000 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 NaN NaN 0.500000000000000 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0.500000000000000 0.500000000000000 NaN NaN 0 0 0 0 0 NaN NaN NaN 0 0 0.500000000000000 0.500000000000000 NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN NaN 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 NaN 0 1 1 1 1 1 0 0 0 NaN NaN 0 0 0 NaN NaN 0 1 1 1 0 0 0 0 0 NaN 0 NaN NaN NaN 0 NaN 0 1 0 0 0 0 0 0 0 NaN 0 NaN NaN NaN 0 NaN 0 1 0 0 0 0 0 0 0 NaN NaN 0 0 0 NaN NaN 0 1 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN 0 1 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 NaN 0 1 0 0 0 0 0 0 0 NaN 0 NaN 0 NaN NaN NaN 0 1 0 0 0 0 0 0 0 NaN 0 NaN 0 NaN NaN NaN 0.500000000000000 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 NaN NaN 0.500000000000000 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0.500000000000000 0.500000000000000 NaN NaN 0 0 0 0 0 NaN NaN NaN 0 0 0.500000000000000 0.500000000000000 NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN NaN 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 NaN 0 1 1 1 1 1 0 0 0 NaN NaN 0 0 0 NaN NaN 0 1 1 1 0 0 0 0 0 NaN 0 NaN NaN NaN 0 NaN 0 1 0 0 0 0 0 0 0 NaN 0 NaN NaN NaN 0 NaN 0 1 0 0 0 0 0 0 0 NaN NaN 0 0 0 NaN NaN 0 1 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN 0 1 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 NaN 0 1 0 0 0 0 0 0 0 NaN 0 NaN 0 NaN NaN NaN 0 1 0 0 0 0 0 0 0 NaN 0 NaN 0 NaN NaN NaN 0.500000000000000 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 NaN NaN 0.500000000000000 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0.500000000000000 0.500000000000000 NaN NaN 0 0 0 0 0 NaN NaN NaN 0 0 0.500000000000000 0.500000000000000 NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN NaN 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN 0 0 0 NaN NaN],[16 16 3]),... % Icon data for 'Load Image'
                'ClickedCallback', @(src,evnt)load_image(this)); % Callback function

            % Zoom Button (Toggle Tool)
            uitoggletool(...
                'Parent', hToolbar,...
                'Tag','Zoom',...
                'TooltipString','Zoom',...
                'CData', reshape([NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN 0 0 0 0 0 0 NaN 0 0 0 0 0 NaN 0 NaN NaN 0 0 1 1 0 0 NaN NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 1 1 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN 0 0 0 0 0 0 NaN 0 0 0 0 0 NaN 0 NaN NaN 0 0 1 1 0 0 NaN NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 1 1 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 NaN NaN 0 0 0 0 0 0 NaN 0 0 0 0 0 NaN 0 NaN NaN 0 0 1 1 0 0 NaN NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN 0 NaN NaN NaN 0 NaN 0 0 1 1 1 1 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 1 1 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0 0 0.500000000000000 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0.500000000000000 0.500000000000000 NaN NaN NaN NaN],[16 16 3]),... % Icon data for 'Zoom'
                'Separator','on',...
                'ClickedCallback', @(src,evnt)set_zoom(src,'hFig',this.hFig)); % Callback uses external set_zoom function

            % Pan Button (Toggle Tool)
            uitoggletool(...
                'Parent', hToolbar,...
                'Tag','Pan',...
                'TooltipString','Pan',...
                'CData', reshape([NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN 0 0 0 0 0 NaN 0 0 NaN 0 0 0 0 0 NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN 0 NaN NaN NaN 0 0 NaN NaN NaN 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN],[16 16 3]),... % Icon data for 'Pan'
                'ClickedCallback', @(src,evnt)set_pan(src,'hFig',this.hFig)); % Callback uses external set_pan function

            % Open Documentation Button
            uipushtool(...
                'Parent', hToolbar,...
                'TooltipString','Open Documentation',...
                'CData', reshape([NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN 0 0 0 0 0 0 0 0 0 0 NaN NaN NaN NaN NaN NaN NaN NaN 0 0 0 0 0 0 NaN NaN NaN NaN NaN],[16 16 3]),... % Icon data for 'Documentation'
                'Separator','on',...
                'ClickedCallback', @(src,evnt)open_doc(this)); % Callback function
            
            % --- Image Display Panels ---
            
            % Panel for RAW Image (Top Left)
            hPanelRaw = uipanel(...
                'Units','normalized',...
                'backgroundcolor','k',...
                'Position',[0 1/2 1/2 1/2]); % Position: [left bottom width height]
            this.RAW.hAx = axes(...
                'Parent',hPanelRaw,...
                'Units','normalized',...
                'Position', [0 0 1 1],...
                'Box','on');
            this.RAW.hImage = image(0,'Parent',this.RAW.hAx,'CdataMapping','scaled');
            set(this.RAW.hAx,'Xticklabel','','Yticklabel','') % Hide axis labels
            this.RAW.hTxtImage = text(1,1,'RAW',...
                'HorizontalAlignment','center',...
                'VerticalAlignment','middle',...
                'Color','k',...
                'Fontsize',25); % Text overlay
            
            % Panel for SEGMENTATION Mask (Bottom Right)
            hPanelProc = uipanel(...
                'Units','normalized',...
                'backgroundcolor','k',...
                'Position',[1/2 0 1/2 1/2]);
            this.MASK.hAx = axes(...
                'Parent',hPanelProc,...
                'Units','normalized',...
                'Position', [0 0 1 1],...
                'Box','on');
            this.MASK.hImage = image(0,'Parent',this.MASK.hAx,'CdataMapping','scaled');
            set(this.MASK.hAx,'Xticklabel','','Yticklabel','') % Hide axis labels
            this.MASK.hTxtImage = text(1,1,'SEGMENTATION',...
                'HorizontalAlignment','center',...
                'VerticalAlignment','middle',...
                'Color','k',...
                'Fontsize',25); % Text overlay
            
            % Panel for PROCESSED/DECONVOLVED Image (Top Right)
            hPanelMask = uipanel(...
                'Units','normalized',...
                'backgroundcolor','k',...
                'Position',[1/2 1/2 1/2 1/2]);
            this.PROC.hAx = axes(...
                'Parent',hPanelMask,...
                'Units','normalized',...
                'Position', [0 0 1 1],...
                'Box','on');
            this.PROC.hImage = image(0,'Parent',this.PROC.hAx,'CdataMapping','scaled');
            set(this.PROC.hAx,'Xticklabel','','Yticklabel','') % Hide axis labels
            this.PROC.hTxtImage = text(1,1,'DECONVOLVED',...
                'HorizontalAlignment','center',...
                'VerticalAlignment','middle',...
                'Color','k',...
                'Fontsize',25); % Text overlay
            
            % --- Settings Panel (Bottom Left) ---
            
            hPanelSetting = uipanel(...
                'Units','normalized',...
                'backgroundcolor','w',...
                'Position',[0 0 1/2 1/2]);
            
            % Toggle Boundary Button
            this.RAW.hToggleBoundary = uicontrol(...
                'Parent',hPanelSetting,...
                'Style', 'togglebutton',...
                'Units','normalized',...
                'Position', [0 0.9 0.5 0.1],...
                'FontUnits','normalized',...
                'FontSize', 0.5,...
                'String', 'Show Boundary',...
                'Callback', @(src,evnt)update_all(this));
            
            % Upsample Static Text Label
            uicontrol(...
                'Parent', hPanelSetting,...
                'Style', 'Edit',...
                'Enable','inactive',... % Acts as a read-only label
                'Units','normalized',...
                'Position', [0.5 0.9 0.3 0.1],...
                'String', 'Upsample:',...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'backgroundcolor','w',...
                'HorizontalAlignment', 'center');
            
            % Upsample Edit Box
            this.hUpsampleEdit = uicontrol(...
                'Parent', hPanelSetting,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [0.8 0.9 0.2 0.1],...
                'FontUnits','normalized',...
                'FontSize',0.5,...
                'String', this.UpsampleFac,...
                'TooltipString',sprintf('Factor by which each image pixel\nis subdivided to generate finer phase boundaries.'),...
                'Callback', @(src,evnt)set_upsample_fac(this,src));
            
            % Correct Illumination Toggle Button
            this.hCorrIlluToggle = uicontrol(...
                'Parent',hPanelSetting,...
                'Style', 'togglebutton',...
                'Units','normalized',...
                'Position', [0 0.8 1 0.1],...
                'FontUnits','normalized',...
                'FontSize', 0.5,...
                'String', 'Correct Illumination',...
                'TooltipString',sprintf('Corrects for the spatially inhomogeneous (non-flat) TIRF illumination profile.'),...
                'Callback', @(src,evnt)correct_illumination(this),...
                'Enable','off'); % Initially disabled until image is loaded
            
            % --- Deconvolution Settings Panel ---
            hPanelDeconvSettings = uipanel(...
                'Parent',hPanelSetting,...
                'Title','Deconvolution Settings:',...
                'TitlePosition','centertop',...
                'Units','normalized',...
                'FontUnits','normalized',...
                'FontSize',0.2,...
                'backgroundcolor','w',...
                'Position',[0 0.45 1 0.35]);
            
            % PSF Width Label
            uicontrol(...
                'Parent', hPanelDeconvSettings,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0 1/2 4/10 1/2],...
                'String', sprintf('PSF Width [px]:'),...
                'FontUnits','normalized',...
                'FontSize',0.4,...
                'backgroundcolor','w',...
                'HorizontalAlignment', 'center');
            
            % PSF Width Slider
            this.hPsfSlider = uicontrol(...
                'Parent', hPanelDeconvSettings,...
                'Style', 'slider',...
                'Units', 'normalized',...
                'Position', [4/10 1/2 4/10 1/2],...
                'Min', this.PsfWidthMin,...
                'Max', this.PsfWidthMax,...
                'Value', this.PsfWidth,...
                'TooltipString',sprintf('The Microscopes'' Point Spread Function (PSF) defines the\npoint dispersion (Std. of the Gaussian approximation)\nobserved in the Fluorescence Imagedue to light diffraction at the Objective.'),...
                'SliderStep', [0.05/(this.PsfWidthMax-this.PsfWidthMin+1),... % Small step size
                0.15/(this.PsfWidthMax-this.PsfWidthMin+1)]); % Large step size
            % Listener for continuous slider updates
            addlistener(this.hPsfSlider,'ContinuousValueChange',...
                @(src,event)set_psf_width(this,src));
            
            % PSF Width Edit Box
            this.hPsfEdit = uicontrol(...
                'Parent', hPanelDeconvSettings,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [8/10 1/2 2/10 1/2],...
                'FontUnits','normalized',...
                'FontSize',0.4,...
                'String', this.PsfWidth,...
                'TooltipString',sprintf('The Microscopes'' Point Spread Function (PSF) defines the\npoint dispersion (Std. of the Gaussian approximation)\nobserved in the Fluorescence Imagedue to light diffraction at the Objective.'),...
                'Callback', @(src,evnt)set_psf_width(this,src));
            
            % Regularization Label
            uicontrol(...
                'Parent', hPanelDeconvSettings,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0 0 4/10 1/2],...
                'String', sprintf('Regularization:'),...
                'FontUnits','normalized',...
                'FontSize',0.4,...
                'backgroundcolor','w',...
                'HorizontalAlignment', 'center');
            
            % Gamma/Regularization Slider
            this.hGammaSlider = uicontrol(...
                'Parent', hPanelDeconvSettings,...
                'Style', 'slider',...
                'Units', 'normalized',...
                'Position', [4/10 0 4/10 1/2],...
                'Min', this.GammaMin,...
                'Max', this.GammaMax,...
                'Value', this.Gamma,...
                'TooltipString',sprintf('The Regularization forces the deconvolved image to be smooth. This regularization improves the conditioning of the problem, thus enabling a direct numerical solution.'),...
                'SliderStep', [0.1/(this.GammaMax-this.GammaMin),...
                1/(this.GammaMax-this.GammaMin)]);
            % Listener for continuous slider updates
            addlistener(this.hGammaSlider,'ContinuousValueChange',...
                @(src,event)set_gamma(this,src));
            
            % Gamma/Regularization Edit Box
            this.hGammaEdit = uicontrol(...
                'Parent', hPanelDeconvSettings,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [8/10 0 2/10 1/2],...
                'FontUnits','normalized',...
                'FontSize',0.4,...
                'String', this.Gamma,...
                'TooltipString',sprintf('The Regularization forces the deconvolved image to be smooth.'),...
                'Callback', @(src,evnt)set_gamma(this,src));
            
            % --- Segmentation Settings Panel ---
            hPanelOtsuSettings = uipanel(...
                'Parent',hPanelSetting,...
                'Title','Segmentation Settings:',...
                'TitlePosition','centertop',...
                'Units','normalized',...
                'FontUnits','normalized',...
                'FontSize',0.2,...
                'backgroundcolor','w',...
                'Position',[0 0.1 1 0.35]);
            
            % # Levels Label
            uicontrol(...
                'Parent', hPanelOtsuSettings,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0 1/2 4/10 1/2],...
                'String', sprintf('# Levels:'),...
                'FontUnits','normalized',...
                'FontSize',0.4,...
                'backgroundcolor','w',...
                'HorizontalAlignment', 'center');
            
            % # Levels Slider
            this.hNumLvlSlider = uicontrol(...
                'Parent', hPanelOtsuSettings,...
                'Style', 'slider',...
                'Units', 'normalized',...
                'Position', [4/10 1/2 4/10 1/2],...
                'Min', this.NumLvlMin,...
                'Max', this.NumLvlMax,...
                'Value', this.NumLvl,...
                'TooltipString',sprintf('Total number of groups the image intensities are classified into.'),...
                'SliderStep', [1/3,1/3]);
            % Listener for continuous slider updates
            addlistener(this.hNumLvlSlider,'ContinuousValueChange',...
                @(src,event)set_num_lvl(this,src));
            
            % # Levels Edit Box
            this.hNumLvlEdit = uicontrol(...
                'Parent', hPanelOtsuSettings,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [8/10 1/2 2/10 1/2],...
                'FontUnits','normalized',...
                'FontSize',0.4,...
                'String', this.NumLvl,...
                'TooltipString',sprintf('Total number of groups the image intensities are classified into.'),...
                'Callback', @(src,evnt)set_num_lvl(this,src));
            
            % Lo Phase Label
            uicontrol(...
                'Parent', hPanelOtsuSettings,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [0 0 1/4 1/2],...
                'String', sprintf('Lo <='),...
                'FontUnits','normalized',...
                'FontSize',0.4,...
                'backgroundcolor','w',...
                'HorizontalAlignment', 'center');
            
            % Lo Level Edit Box
            this.hLoLvlEdit = uicontrol(...
                'Parent', hPanelOtsuSettings,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [1/4 0 1/4 1/2],...
                'FontUnits','normalized',...
                'FontSize',0.4,...
                'String', this.LoLvl,...
                'TooltipString',sprintf('Last group index including the lipid ordered phase (Lo).'),...
                'Callback', @(src,evnt)set_lo_lvl(this,src));
            
            % Ld Phase Label
            uicontrol(...
                'Parent', hPanelOtsuSettings,...
                'Style', 'Edit',...
                'Enable','inactive',...
                'Units','normalized',...
                'Position', [2/4 0 1/4 1/2],...
                'String', sprintf('Ld >='),...
                'FontUnits','normalized',...
                'FontSize',0.4,...
                'backgroundcolor','w',...
                'HorizontalAlignment', 'center');
            
            % Ld Level Edit Box
            this.hLdLvlEdit = uicontrol(...
                'Parent', hPanelOtsuSettings,...
                'Style', 'edit',...
                'Units','normalized',...
                'Position', [3/4 0 1/4 1/2],...
                'FontUnits','normalized',...
                'FontSize',0.4,...
                'String', this.LdLvl,...
                'TooltipString',sprintf('First group index including the lipid disordered phase (Ld).'),...
                'Callback', @(src,evnt)set_ld_lvl(this,src));
            
            % Export Mask Button
            uicontrol(...
                'Parent',hPanelSetting,...
                'Style', 'pushbutton',...
                'Units','normalized',...
                'Position', [0 0 1 0.1],...
                'FontUnits','normalized',...
                'FontSize', 0.5,...
                'String', 'Export Mask',...
                'Callback', @(src,evnt)export_mask(this));
            
            % Set default colormap for the figure
            colormap('gray')
        end %fun

        %%
        function load_image(this)
            [fileName,filePath,isOK] = uigetfile('.tif','Load Image',this.WorkPath);
            if isOK
                fileImg = fullfile(filePath,fileName);
                this.WorkPath = filePath;

                this.RAW.Src = double(imread(fileImg,1));
                upsample_image(this)

                set([this.RAW.hTxtImage,this.MASK.hTxtImage,this.PROC.hTxtImage],'visible','off')
            end %if
        end %fun

        %%
        function img = get_raw(this)
            if get(this.hCorrIlluToggle,'Value')
                img = this.RAW.DataCorr;
            else
                img = this.RAW.Data;
            end %if
        end %fun

        %%
        function set_upsample_fac(this,src)
            value = round(str2double(get(src,'String')));
            value = min(10,max(1,value));

            this.UpsampleFac = value;
            set(this.hUpsampleEdit,'String',value)

            upsample_image(this)
        end %fun
        function set_psf_width(this,src)
            switch get(src,'Style')
                case 'slider'
                    value = get(src,'Value');
                case 'edit'
                    value = str2double(get(src,'String'));
            end %switch
            value = min(this.PsfWidthMax,max(this.PsfWidthMin,value));
            value = rnd2dec(value,2);

            this.PsfWidth = value;
            set(this.hPsfEdit,'String',value)
            set(this.hPsfSlider,'Value',value)

            deconvolve_image(this)
        end %fun
        function set_gamma(this,src)
            switch get(src,'Style')
                case 'slider'
                    value = get(src,'Value');
                case 'edit'
                    value = str2double(get(src,'String'));
            end %switch
            value = min(this.GammaMax,max(this.GammaMin,value));
            value = rnd2dec(value,2);

            this.Gamma = value;
            set(this.hGammaEdit,'String',value)
            set(this.hGammaSlider,'Value',value)

            deconvolve_image(this)
        end %fun
        function set_num_lvl(this,src)
            switch get(src,'Style')
                case 'slider'
                    value = round(get(src,'Value'));
                case 'edit'
                    value = round(str2double(get(src,'String')));
            end %switch
            value = min(this.NumLvlMax,max(this.NumLvlMin,value));

            this.NumLvl = value;
            set(this.hNumLvlEdit,'String',value)
            set(this.hNumLvlSlider,'Value',value)

            this.LdLvl = min(this.NumLvl,max(this.LoLvl,this.LdLvl));
            set(this.hLdLvlEdit,'String',this.LdLvl)

            this.LoLvl = min(this.LdLvl-1,max(1,this.LoLvl));
            set(this.hLoLvlEdit,'String',this.LoLvl)

            gen_mask(this)
        end %fun

        function set_lo_lvl(this,src)
            value = round(str2double(get(src,'String')));
            value = min(this.LdLvl-1,max(1,value));

            this.LoLvl = value;
            set(this.hLoLvlEdit,'String',value)

            gen_mask(this)
        end %fun
        function set_ld_lvl(this,src)
            value = round(str2double(get(src,'String')));
            value = min(this.NumLvl,max(this.LoLvl+1,value));

            this.LdLvl = value;
            set(this.hLdLvlEdit,'String',value)

            gen_mask(this)
        end %fun

        %%
        function upsample_image(this)
            if isfield(this.RAW,'Src')
                if this.UpsampleFac == 1
                    this.RAW.Data = this.RAW.Src;
                else
                    this.RAW.Data = imresize(this.RAW.Src,this.UpsampleFac);
                end %if
                [this.RAW.Height,this.RAW.Width] = size(this.RAW.Data);

                correct_illumination(this)
                linkaxes([this.RAW.hAx this.PROC.hAx this.MASK.hAx],'xy')
                axis([this.RAW.hAx this.PROC.hAx this.MASK.hAx],'image','ij')

                set([this.RAW.hAx this.PROC.hAx this.MASK.hAx],'xlim',[1 this.RAW.Width],'ylim',[1 this.RAW.Height])
                set([this.RAW.hAx this.PROC.hAx this.MASK.hAx],'xlimmode','auto','ylimmode','auto')
                zoom reset
            end %if
        end %fun
        function correct_illumination(this)
            if isfield(this.RAW,'Data')
                if get(this.hCorrIlluToggle,'value')
                    %not yet implemented
                else
                    this.RAW.DataCorr = [];
                end %if
                deconvolve_image(this)
            end %if
        end %fun
        function deconvolve_image(this)
            if isfield(this.RAW,'Data')
                sigGauss = this.PsfWidth*this.UpsampleFac;
                gamma = 10^this.Gamma;

                imgPSF = zeros(this.RAW.Height,this.RAW.Width);
                supportGauss = ceil(6*sigGauss+1);
                if not(mod(supportGauss,2))
                    supportGauss = supportGauss + 1;
                end
                imgPSF(1:supportGauss,1:supportGauss) = fspecial(...
                    'gaussian',[supportGauss supportGauss],sigGauss);
                imgPSF = circshift(imgPSF, [-1 -1]*floor(supportGauss/2));
                imgPSF = fftn(imgPSF);

                this.PROC.Data = real(ifftn(conj(imgPSF).*...
                    fftn(get_raw(this))./(abs(imgPSF).^2 + gamma)));

                gen_mask(this)
            end %if
        end %fun
        function gen_mask(this)
            if isfield(this.RAW,'Data')
                this.MASK.Data = imquantize(this.PROC.Data,...
                    multithresh(this.PROC.Data,this.NumLvl));

                this.MASK.Lo = (this.MASK.Data <= this.LoLvl); %-> Lo-Phase
                this.MASK.LoBndry = bwperim(this.MASK.Lo);
                this.MASK.Ld = (this.MASK.Data >= this.LdLvl); %-> Ld-Phase
                this.MASK.LdBndry = bwperim(this.MASK.Ld);

                update_all(this)
            end %if
        end %fun

        %%
        function update_all(this)
            if isfield(this.RAW,'Src')
                update_proc(this)
                update_mask(this)
            end %if
        end %fun
        function update_proc(this)
            %             set(this.PROC.hImage,...
            %                 'Cdata',norm2quantile(this.PROC.Data,[0.01 0.99]))

            imgRaw = norm2quantile(this.PROC.Data,[0.01 0.99]);
            if get(this.RAW.hToggleBoundary,'Value')
                set(this.PROC.hImage,...
                    'Cdata',IMG_to_RGB(...
                    min(1,imgRaw+this.MASK.LoBndry),...
                    min(1,imgRaw+this.MASK.LdBndry),...
                    imgRaw,[]))
            else
                set(this.PROC.hImage,...
                    'Cdata',imgRaw)
            end %if
        end %fun
        function update_mask(this)
            set(this.MASK.hImage,...
                'Cdata',IMG_to_RGB(...
                this.MASK.Lo,...
                this.MASK.Ld,[],[]))

            imgRaw = norm2quantile(this.RAW.Data,[0.01 0.99]);
            if get(this.RAW.hToggleBoundary,'Value')
                set(this.RAW.hImage,...
                    'Cdata',IMG_to_RGB(...
                    min(1,imgRaw+this.MASK.LoBndry),...
                    min(1,imgRaw+this.MASK.LdBndry),...
                    imgRaw,[]))
            else
                set(this.RAW.hImage,...
                    'Cdata',imgRaw)
            end %if
        end %fun

        %%
        function export_mask(this)
            if isfield(this.RAW,'Src')
                pathname = uigetdir(this.WorkPath);
                folder = 'Lipid Phase Segmentation';
                mkdir(pathname,folder)

                imwrite(this.MASK.Lo==1,fullfile(pathname,folder,'Lo-Phase Mask.tif'),...
                    'Compression','none')
                imwrite(this.MASK.Ld==1,fullfile(pathname,folder,'Ld-Phase Mask.tif'),...
                    'Compression','none')
                imwrite(uint8(norm2quantile(this.PROC.Data,[0 1])*255),...
                    fullfile(pathname,folder,'Lipid Phase Deconvolution.tif'),...
                    'Compression','none')

                generate_information_dialog('',{'Phase Mask saved'})
            end %if
        end %fun

        function open_doc(this)
            generate_information_dialog('Lipid Phase Segmentizer',...
                {'Copyright (c) 2025 Christian Paolo Richter',...
                'University of Osnabrueck'})
        end %fun
    end %methods
end %class